# Phase 9 — public read-only calendar at /c/:token. The share token
# (User#public_token, generated by the ensure_public_token callback when the
# calendar is made public in account settings) is the capability: anyone
# holding the link can browse the owner's visible week read-only, download
# the scheduled routes' GPX files (public signed-id endpoint) and join rides
# onto their own calendar. A disabled share or unknown token 404s. Guests
# clicking Join get the intent parked in session — after sign-in / sign-up,
# ApplicationController#after_sign_in_path_for finishes the join for them.
class PublicCalendarController < ApplicationController
  include CalendarWeekSupport

  skip_before_action :authenticate_user!

  # GET /c/:token?week=YYYY-MM-DD — read-only week view of the shared calendar.
  # Renders the same calendars/show template as my/friend views; the public
  # branch keys off @is_public_view (plain-text titles, join docks, no dnd).
  def show
    prepare_shared_owner
    @is_public_view = true
    @week_start = resolve_week_start
    # Same total order as CalendarsController#show (date, start time, id
    # tiebreaker) so same-time entries render in a stable order here too.
    @week_entries = @owner.calendar_entries
                          .includes(:route)
                          .between(@week_start..(@week_start + 6))
                          .order(:scheduled_on, :start_time, :id).to_a
    @telemetry = build_telemetry(@week_entries)
    # Visitors see only the routes scheduled in the visible week (the same
    # privacy contract as the friend view) — never the whole library.
    @sidebar_routes = @week_entries.sort_by(&:calendar_sort_key).map(&:route).uniq
    # Which of this week's rides the signed-in visitor already joined — the
    # docks show the inert "Joined" state for them, stable across reloads.
    @joined_origin_ids =
      if user_signed_in?
        current_user.calendar_entries
                    .where(origin_entry_id: @week_entries.map(&:id))
                    .pluck(:origin_entry_id)
      else
        []
      end

    render "calendars/show"
  end

  # POST /c/:token/join — "add to my calendar" from the public share: the
  # same semantics as the friend view's Join (deep-copy + own entry, linked
  # via origin_entry, idempotent via CalendarEntry.join_ride!). Signed-in
  # visitors stay on the public page — the dock swaps to "Joined" in place;
  # guests park the join intent in session, and the sign-in / sign-up flow
  # completes it (see ApplicationController#after_sign_in_path_for).
  def join
    prepare_shared_owner
    origin_entry = @owner.calendar_entries.find(params[:entry_id])

    unless user_signed_in?
      # Park the join intent — Devise's after_sign_in_path_for completes it
      # right after sign-in / sign-up and lands on the shared week. (Storing
      # the POST URL itself would send a GET at this POST-only route.)
      session[:pending_public_join] = { token: params[:token], entry_id: origin_entry.id, week: params[:week] }
      return redirect_to new_user_session_path,
                         alert: "Sign in to add \"#{origin_entry.route.title}\" to your calendar."
    end

    joined_entry = CalendarEntry.join_ride!(origin_entry, owner: current_user)

    respond_to do |format|
      format.turbo_stream do
        @entry = origin_entry
        @is_public_view = true # the stream repaints the public-view card
        # Same week-context contract as the calendar streams, so the repaint
        # templates can read @week_start instead of crashing on nil.
        @week_start = resolve_week_start
        # The mobile day-panel repaint needs the week's entries; its entry
        # card derives the "Joined" dock state from this set.
        @week_entries = @owner.calendar_entries
                              .includes(:route)
                              .between(@week_start..(@week_start + 6)).to_a
        @joined_origin_ids = [ origin_entry.id ]
        render :join
      end
      format.html do
        redirect_to public_calendar_path(@owner.public_token, week: params[:week]),
                    notice: "You joined \"#{joined_entry.route.title}\" — it is on your calendar for " \
                            "#{joined_entry.scheduled_on.strftime('%b %-d')}."
      end
    end
  rescue ActiveRecord::RecordInvalid => e
    redirect_to public_calendar_path(@owner.public_token, week: params[:week]),
                alert: "Could not join route: #{e.message}"
  end

  private

  # Resolve + authorize the shared calendar's owner. Only live shares are
  # reachable: unknown tokens and calendars made private again (token
  # cleared by the callback) both 404.
  def prepare_shared_owner
    @owner = User.find_by(public_token: params[:token])
    raise ActiveRecord::RecordNotFound unless @owner&.calendar_public?
  end
end
